# profiles/slurm/config.yaml
jobname: "em_vcf_{rule}"
cluster: >-
  sbatch
  sbatch
  --cpus-per-task={threads}
  --mem={resources.mem_mb}M
  --time={resources.time}
  --partition=low
  --mail-user=srichards@ucdavis.edu
  --account=jbondgrp
  --cpus-per-task={threads}
  --mem={resources.mem_mb}M
  --output=slurm_logs/{rule}-%A_%j.out
  --error=slurm_logs/{rule}-%A_%j.err

default-resources:
  mem_mb: 64000
  time: "12:00:00"
keep-going: true
rerun-incomplete: true
latency-wait: 120
use-conda: false
